version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '3003:5432'
    volumes:
      - postgres_db:/data/postgres
      # - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.docker

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - '5050:80'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
  #     PGADMIN_DEFAULT_PASSWORD: mypgadminpass
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres

volumes:
  postgres_db:
  # postgres_data:
  # pgadmin_data:
